export default [
    'Hotfish',
    'Broccoli',
    'Wriggling Grub',
    'Joint Of Ham',
    'Rainbow Negg',
    'Streaky Bacon',
    'Ultimate Burger',
    'Bacon Muffin',
    'Hot Cakes',
    'Spicy Wings',
    'Apple Onion Rings',
    'Sushi',
    'Negg Stew',
    'Ice Chocolate Cake',
    'Strochal',
    'Mallowicious Bar',
    'Fungi Pizza',
    'Broccoli and Cheese Pizza',
    'Bubbling Blueberry Pizza',
    'Grapity Slush',
    'Rainborific Slush',
    'Tangy Tropic Slush',
    'Blueberry Tomato Blend',
    'Lemon Blitz',
    'Fresh Seaweed Pie',
    'Flaming Burnumup',
    'Hot Tyrannian Pepper',
    'Eye Candy',
    'Cheese and Tomato Sub',
    'Asparagus Pie',
    'Wild Chocomato',
    'Cinnamon Swirl',
    'Anchovies',
    'Flaming Fire Faerie Pizza',
    'Orange Negg',
    'Fish Negg',
    'Super Lemon Grape Slush',
    'Rasmelon',
    'Mustard Ice Cream',
    'Worm and Leech Pizza',
];
